---
title: "Informe No 20"
output:
  html_notebook: 
    toc: TRUE
    toc_float: TRUE
  pdf_document: default
editor_options:
  chunk_output_type: inline

  
---
Manizales 16 de marzo de 2022

Referencia: Informe  del 23 al 30 de marzo


```{r echo=, message=FALSE, warning=FALSE}

library(googlesheets4)
library(tidyverse)
library(ggpubr)
library(gpairs)
library(PerformanceAnalytics)
library(lubridate)
library(ggplot2)
library(readr)
library(readxl)
library(googleAnalyticsR)
library(tosr)
library(igraph)
library(tidytext)
library(colourpicker)
library(colorspace)





```

Getting data 

```{r message=FALSE, warning=FALSE}
facebook <- read_csv("https://docs.google.com/spreadsheets/d/1iv_7lBeondfTiLN_kLRnAW-9UnmT4lw6RVQxCuSD0vY/export?format=csv&gid=1112529965", col_types = cols()) |> 
  mutate(Date = mdy(Date))

youtube <- read_csv("https://docs.google.com/spreadsheets/d/1iv_7lBeondfTiLN_kLRnAW-9UnmT4lw6RVQxCuSD0vY/export?format=csv&gid=1622987274", col_types = cols())
  
facebook[is.na(facebook)] <- 0
linkedind <- read_csv("https://docs.google.com/spreadsheets/d/1iv_7lBeondfTiLN_kLRnAW-9UnmT4lw6RVQxCuSD0vY/export?format=csv&gid=712028608") |>
   mutate(date = mdy(date))

facebook |> dim()
#twitter <- read_sheet("https://docs.google.com/spreadsheets/d/1kM1IZfCGWZ8k-jFlx4Ak-OIEp-3MVRdCpvV00DXmNiI/edit#gid=1214992278", sheet = "twitter")

google_analytics <- read_csv("https://docs.google.com/spreadsheets/d/1iv_7lBeondfTiLN_kLRnAW-9UnmT4lw6RVQxCuSD0vY/export?format=csv&gid=1575918127")
  
  
```



# Facebook

## Global Analysis 1

```{r message=FALSE, warning=FALSE}
total_likes <- 
  facebook %>% 
  select(Date, Lifetime_Total_Likes) %>% 
  ggplot(aes(x = Date, y = Lifetime_Total_Likes,)) +
  geom_line() +
  geom_point() +
  ggtitle("Total likes acummulated per day") +
  ylab("Total likes")





total_engagement <- 
  facebook %>% 
  select(Date, Weekly_Page_Engaged_Users) %>% 
  ggplot(aes(x = Date, y = Weekly_Page_Engaged_Users)) +
  geom_line() +
  geom_point() +
  ggtitle("Total engaged acummulated per day") +
  ylab("Total engaged")

total_reach <- 
  facebook %>% 
  select(Date, Weekly_Total_Reach ) %>% 
  ggplot(aes(x = Date, y = Weekly_Total_Reach)) +
  geom_line() +
  geom_point() +
  ggtitle("Total reach acummulated per day") +
  ylab("Total reach")

total_impresions <-
  facebook %>% 
  select(Date, Weekly_Total_Impressions) %>% 
  ggplot(aes(x = Date, y = Weekly_Total_Impressions)) +
  geom_line() +
  geom_point() +
  ggtitle("Total impressions acummulated per day") +
  ylab("Total Impressions")

global_analysis <- 
  ggarrange(total_likes, 
            total_engagement, 
            total_reach,
            total_impresions,
      
            labels = c("A", "B", "C", "D"),
            ncol = 2, nrow = 2)
global_analysis

```


## Global Analysis 2

```{r message=FALSE, warning=FALSE}
total_daily_likes <- 
  facebook %>% 
  select(Date, Daily_New_Likes) %>% 
  ggplot(aes(x = Date, y = Daily_New_Likes)) +
  geom_line() +
  geom_point() +
  ggtitle("Daily New Likes") +
  ylab("Total daily likes")

total_daily_engagement <- 
  facebook %>% 
  select(Date, Daily_Page_Engaged_Users) %>% 
  ggplot(aes(x = Date, y = Daily_Page_Engaged_Users )) +
  geom_line() +
  geom_point() +
  ggtitle("Daily new engaged ") +
  ylab("Total daily engaged")

total_daily_reach <- 
  facebook %>% 
  select(Date, Daily_Total_Reach) %>% 
  ggplot(aes(x = Date, y = Daily_Total_Reach)) +
  geom_line() +
  geom_point() +
  ggtitle("Daily new reach") +
  ylab("Total daily reach")

total_daily_impresions <-
  facebook %>% 
  select(Date, Daily_Total_Impressions) %>% 
  ggplot(aes(x = Date, y = Daily_Total_Impressions)) +
  geom_line() +
  geom_point() +
  ggtitle("Daily New Impressions") +
  ylab("Total daily Impressions")

global_analysis <- 
  ggarrange(total_daily_likes, 
            total_daily_engagement, 
            total_daily_reach,
            total_daily_impresions,
            labels = c("A", "B", "C", "D"),
            ncol = 2, nrow = 2)
global_analysis

```



## Past week



```{r message=FALSE, warning=FALSE}
facebook_week <- 
  facebook %>% 
  filter(Date >= "2022-02-08") %>% 
  mutate(Date = lubridate::wday(Date, label = TRUE))

total_daily_likes_week <- 
  facebook_week %>% 
  select(Date, Daily_New_Likes) %>% 
  ggplot(aes(x = Date, y = Daily_New_Likes, group = 1)) +
  geom_point() +
  geom_line() +
  ggtitle("Daily New Likes") +
  ylab("Total daily likes")

total_daily_engagement_week <- 
  facebook_week %>% 
  select(Date, Daily_Page_Engaged_Users) %>% 
  ggplot(aes(x = Date, y = Daily_Page_Engaged_Users, group = 1 )) +
  geom_line() +
  geom_point() +
  ggtitle("Daily new engaged ") +
  ylab("Total daily engaged")

total_daily_reach_week <- 
  facebook_week %>% 
  select(Date, Daily_Total_Reach) %>% 
  ggplot(aes(x = Date, y = Daily_Total_Reach, group = 1)) +
  geom_line() +
  geom_point() +
  ggtitle("Daily new reach") +
  ylab("Total daily reach")

total_daily_impresions_week <-
  facebook_week %>% 
  select(Date, Daily_Total_Impressions) %>% 
  ggplot(aes(x = Date, y = Daily_Total_Impressions, group = 1)) +
  geom_line() +
  geom_point() +
  ggtitle("Daily New Impressions") +
  ylab("Total daily Impressions")

global_analysis_week <- 
  ggarrange(total_daily_likes_week, 
            total_daily_engagement_week, 
            total_daily_reach_week,
            total_daily_impresions_week,
            labels = c("A", "B", "C", "D"),
            ncol = 2, nrow = 2)
global_analysis_week
```
 

# Twitter

```{r}
twitter %>% 
  select(Date,Impressions_Tw) %>% 
  ggplot(aes(x = Date, y = Impressions_Tw)) +
  geom_line() +
  ggtitle("Total Impressions twitter ") +
  ylab("Total Impressions")
  
twitter_week <- 
  twitter %>% 
  filter(Date >= "2020-11-16" & Date < "2020-11-23") %>% 
  mutate(Date = lubridate::wday(Date, label = TRUE)) 

Impressions_tw_week <- 
  twitter_week %>% 
  select(Date, Impressions_Tw) %>% 
  ggplot(aes(x = Date, y = Impressions_Tw, group = 1)) +
  geom_point() +
  geom_line() +
  ggtitle("Daily New Impressions") +
  ylab("Total daily Impressions")

Impressions_tw_week

```


# Youtube 


```{r message=FALSE, warning=FALSE}
total_views <-
  youtube %>% 
  select(Date, Views)
  
ggplot(total_views) +
  geom_line(aes(x=Date, y=Views, color="red")) +
  geom_point(aes(x=Date, y=Views, color= "blue")) +
  ggtitle("Views") +
  ylab("total Views") 
```

```{r message=FALSE, warning=FALSE}
total_Subscribers <-
  youtube %>% 
  select(Date, Subscribers)

ggplot(total_Subscribers) +
  geom_line(aes(x=Date, y=Subscribers,color="red")) +
  geom_point(aes(x=Date, y=Subscribers, color= "blue")) +
  ggtitle("Subscribers") +
  ylab("total_Subscribers")
```

```{r message=FALSE, warning=FALSE}
total_likes <-
  youtube %>% 
  select(Date, likes)
  
ggplot(total_likes) +
  geom_line(aes(x=Date, y=likes, color="red")) +
  geom_point(aes(x=Date, y=likes, color= "blue")) +
  ggtitle("likes") +
  ylab("total likes")

```

```{r message=FALSE, warning=FALSE}
total_impressions <-
  youtube %>% 
  select(Date, impressions)
  
ggplot(total_impressions) +
  geom_line(aes(x=Date, y=impressions, color="red")) +
  geom_point(aes(x=Date, y=impressions, color= "blue")) +
  ggtitle("impresions") +
  ylab("total impresions")

```


```{r message=FALSE, warning=FALSE}
total_shares <-
  youtube %>% 
  select(Date, shares)
  

ggplot(total_shares) +
  geom_line(aes(x=Date, y=shares, color="red")) +
  geom_point(aes(x=Date, y=shares, color= "blue")) +
  ggtitle("shares") +
  ylab("total shares")
```

# linkedind

```{r message=FALSE, warning=FALSE}
total_view <-
  linkedind %>% 
  select(date, Overall_page_views_total)

ggplot(total_view) +
  geom_point(aes(x=date, y=Overall_page_views_total, color= "blue")) +
  geom_line(aes(x=date, y=Overall_page_views_total, color="red")) +
  ggtitle("Overal page views total") +
  ylab("total view")
```

```{r message=FALSE, warning=FALSE}
total_visitors <-
  linkedind %>% 
  select(date, Overall_page_unique_visitors_total) 
ggplot(total_visitors) +
  geom_point(aes(x=date, y=Overall_page_unique_visitors_total, color= "blue"))+
  geom_line(aes(x=date, y=Overall_page_unique_visitors_total, color="red")) +
  ggtitle("Overall page unique visitors total") +
  ylab("total visitors")


```


```{r message=FALSE, warning=FALSE}
page_views <-
  linkedind %>% 
  select(date, Total_Page_Views_Total)
  
ggplot(page_views) +
  geom_point(aes(x=date, y=Total_Page_Views_Total,color= "blue")) +
  geom_line(aes(x=date, y=Total_Page_Views_Total, color= "red")) +
  ggtitle("Page Views Total") +
  ylab("page views")
```



```{r message=FALSE, warning=FALSE}
total_followers <-
  linkedind %>% 
  select(date, followers)
  
ggplot(total_followers) +
  geom_point(aes(x=date, y=followers, color= "blue")) +
  geom_line(aes(x=date, y=followers,color= "red" )) +
  ggtitle("total followers") +
  ylab("followers")

```





```




